### ISSUE TITLE
eColour and eValue interchanged

### ISSUE THREAD

**Issue by derderdunichbist** [derderdunichbist/poker#14]
@SebastianZeeb 
`eColour` has the values = _`TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING, ACE`_

`eValue` has the values = _`CLUBS, DIAMONDS, HEARTS, SPADES`_

This needs to be swapped. I guess it's enough to just rename both of those classes by eclipse refactoring, but please take a look that nothing will damage your code doing so

**Comment by SebastianZeeb** [comment]
Uh lol whoops yep, refactor
